"""
Craniobot: set miling configurations and run milling commands
University of Minnesota - Twin Cities
Biosensing and Biorobotics Lab
author: Daniel Sousa Schulman
email: sousa013@umn.edu // dschul@umich.edu
PI: Suhasa Kodandaramaiah (suhasabk@umn.edu)
"""
from PyQt5 import QtCore, QtGui, QtWidgets
from generate_milling_commands import MillPath
import time
from instructions_Milling import *

class Ui_MillingConfig(object):
    def callJog(self, tinyG):
        XMove=0
        YMove=0
        ZMove=0
        speed=300
        speed_quant=int(self.speed.currentText())
        speed=speed_quant*100
        if(self.XJog.text()):
            XMove=float(self.XJog.text())
            tinyG.jog("x", XMove, int(speed))
        if(self.YJog.text()):
            YMove=float(self.YJog.text())
            tinyG.jog("y", YMove, int(speed))
        if(self.ZJog.text()):
            ZMove=float(self.ZJog.text())
            tinyG.jog("z", ZMove, int(speed))  
        time.sleep(1)
        tinyG.ser.write(b'{"stat":n}\n')
        stat=str(tinyG.ser.readlines())
        val=int(stat[stat.find("stat")+6:stat.find("stat")+7])
        while(val!=3):
            tinyG.ser.write(b'{"stat":n}\n')
            stat=str(tinyG.ser.readlines())
            val=int(stat[stat.find("stat")+6:stat.find("stat")+7])
            time.sleep(1)
        self.updatePosition(tinyG)
    
    def goxyOrigin(self, tinyG):
        tinyG.goToXYOrigin(200)
        time.sleep(1)
        tinyG.ser.write(b'{"stat":n}\n')
        stat=str(tinyG.ser.readlines())
        val=int(stat[stat.find("stat")+6:stat.find("stat")+7])
        while(val!=3):
            tinyG.ser.write(b'{"stat":n}\n')
            stat=str(tinyG.ser.readlines())
            val=int(stat[stat.find("stat")+6:stat.find("stat")+7])
            time.sleep(1)
        self.updatePosition(tinyG)
        
    def updatePosition(self, tinyG):
        tinyG.ser.write(b'{"pos":n}\n')
        pos=str(tinyG.ser.readlines())
        
        initIndex=pos.find("pos")+6
        finalIndex=pos.find("\"a\"")-1
        newPos=pos[initIndex:finalIndex]

        xaxis=int(newPos[newPos.find("x")+3:newPos.find(",")-4])
        newPos=newPos[newPos.find(",")+1:]
        yaxis=int(newPos[newPos.find("y")+3:newPos.find(",")-4])
        newPos=newPos[newPos.find(",")+1:]
        zaxis=int(newPos[newPos.find("z")+3:len(newPos)-4])
        
        self.XValue.display(xaxis)
        self.YValue.display(yaxis)
        self.ZValue.display(zaxis)
    
    def  openInstructions(self):
        self.window = QtWidgets.QDialog()
        self.uiI_Milling = Ui_I_Milling()
        self.uiI_Milling.setupUi(self.window)
        self.window.show()
        
    def runMilling(self, tinyG, probeCommands, Dialog):
        depth=abs(float(self.depthValue.text()))
        depth=depth/1000
        procedure=abs(int(self.procedureNumber.text()))
        counter=1
        for i in probeCommands:
            if (procedure==counter):
                newDepth=i.millingDepth+depth
                milling=MillPath(i.millingPath, newDepth)
                tinyG.runMill(milling.gCode)
                time.sleep(1)
                tinyG.ser.write(b'{"stat":n}\n')
                stat=str(tinyG.ser.readlines())
                val=int(stat[stat.find("stat")+6:stat.find("stat")+7])
                while(val!=3 and val!=4):
                    tinyG.ser.write(b'{"stat":n}\n')
                    stat=str(tinyG.ser.readlines())
                    val=int(stat[stat.find("stat")+6:stat.find("stat")+7])
                    time.sleep(1)
                self.updatePosition(tinyG)
                i.millingDepth=i.millingDepth+depth
            counter=counter+1 
        self.retranslateUi(Dialog, probeCommands)
        
    def origin(self, tinyG):
        tinyG.setOrigin()
        self.updatePosition(tinyG)        
            
    def setupUi(self, Dialog, tinyG, probeCommands):
        Dialog.setObjectName("Dialog")
        Dialog.resize(736, 347)
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(430, -30, 21, 411))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setAutoFillBackground(False)
        self.line.setStyleSheet("color: rgb(0, 0, 0);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(130, 20, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 320, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.instructionText = QtWidgets.QPlainTextEdit(Dialog)
        self.instructionText.setGeometry(QtCore.QRect(240, 60, 181, 241))
        self.instructionText.setObjectName("instructionText")
        self.procedureNumber = QtWidgets.QLineEdit(Dialog)
        self.procedureNumber.setGeometry(QtCore.QRect(190, 180, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.procedureNumber.setFont(font)
        self.procedureNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.procedureNumber.setObjectName("procedureNumber")
        self.depthValue = QtWidgets.QLineEdit(Dialog)
        self.depthValue.setGeometry(QtCore.QRect(190, 220, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.depthValue.setFont(font)
        self.depthValue.setAlignment(QtCore.Qt.AlignCenter)
        self.depthValue.setObjectName("depthValue")
        self.runMill = QtWidgets.QPushButton(Dialog)
        self.runMill.setGeometry(QtCore.QRect(20, 260, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.runMill.setFont(font)
        self.runMill.setObjectName("runMill")
        self.LabelPosition_2 = QtWidgets.QLabel(Dialog)
        self.LabelPosition_2.setGeometry(QtCore.QRect(20, 220, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LabelPosition_2.setFont(font)
        self.LabelPosition_2.setAutoFillBackground(True)
        self.LabelPosition_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LabelPosition_2.setLineWidth(1)
        self.LabelPosition_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelPosition_2.setObjectName("LabelPosition_2")
        self.LabelPosition_3 = QtWidgets.QLabel(Dialog)
        self.LabelPosition_3.setGeometry(QtCore.QRect(20, 180, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LabelPosition_3.setFont(font)
        self.LabelPosition_3.setAutoFillBackground(True)
        self.LabelPosition_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LabelPosition_3.setLineWidth(1)
        self.LabelPosition_3.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelPosition_3.setObjectName("LabelPosition_3")
        self.resetOrigin = QtWidgets.QPushButton(Dialog)
        self.resetOrigin.setGeometry(QtCore.QRect(20, 120, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.resetOrigin.setFont(font)
        self.resetOrigin.setObjectName("resetOrigin")
        self.Instructions = QtWidgets.QPushButton(Dialog)
        self.Instructions.setGeometry(QtCore.QRect(410, 10, 21, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Instructions.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Instructions.setFont(font)
        self.Instructions.setStyleSheet("QPushButton{\n"
"background-color: rgb(225,225,225);\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width: 1px;\n"
"border-radius: 10px;\n"
"}")
        self.Instructions.setObjectName("Instructions")
        self.xyOrigin = QtWidgets.QPushButton(Dialog)
        self.xyOrigin.setGeometry(QtCore.QRect(20, 70, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.xyOrigin.setFont(font)
        self.xyOrigin.setObjectName("xyOrigin")
        self.GoButton = QtWidgets.QPushButton(Dialog)
        self.GoButton.setGeometry(QtCore.QRect(590, 210, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.GoButton.setFont(font)
        self.GoButton.setObjectName("GoButton")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(530, 20, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ZValue = QtWidgets.QLCDNumber(Dialog)
        self.ZValue.setGeometry(QtCore.QRect(520, 160, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ZValue.setFont(font)
        self.ZValue.setAutoFillBackground(False)
        self.ZValue.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.ZValue.setDigitCount(4)
        self.ZValue.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.ZValue.setObjectName("ZValue")
        self.XJog = QtWidgets.QLineEdit(Dialog)
        self.XJog.setGeometry(QtCore.QRect(590, 80, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.XJog.setFont(font)
        self.XJog.setAlignment(QtCore.Qt.AlignCenter)
        self.XJog.setObjectName("XJog")
        self.LabelJog = QtWidgets.QLabel(Dialog)
        self.LabelJog.setGeometry(QtCore.QRect(580, 50, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LabelJog.setFont(font)
        self.LabelJog.setAutoFillBackground(True)
        self.LabelJog.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LabelJog.setLineWidth(1)
        self.LabelJog.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelJog.setObjectName("LabelJog")
        self.LabelPosition = QtWidgets.QLabel(Dialog)
        self.LabelPosition.setGeometry(QtCore.QRect(480, 50, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LabelPosition.setFont(font)
        self.LabelPosition.setAutoFillBackground(True)
        self.LabelPosition.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LabelPosition.setLineWidth(1)
        self.LabelPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelPosition.setObjectName("LabelPosition")
        self.YValue = QtWidgets.QLCDNumber(Dialog)
        self.YValue.setGeometry(QtCore.QRect(520, 120, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.YValue.setFont(font)
        self.YValue.setAutoFillBackground(False)
        self.YValue.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.YValue.setDigitCount(4)
        self.YValue.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.YValue.setObjectName("YValue")
        self.YJog = QtWidgets.QLineEdit(Dialog)
        self.YJog.setGeometry(QtCore.QRect(590, 120, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.YJog.setFont(font)
        self.YJog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.YJog.setAlignment(QtCore.Qt.AlignCenter)
        self.YJog.setObjectName("YJog")
        self.LabelZ = QtWidgets.QLabel(Dialog)
        self.LabelZ.setGeometry(QtCore.QRect(490, 160, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LabelZ.setFont(font)
        self.LabelZ.setTextFormat(QtCore.Qt.PlainText)
        self.LabelZ.setScaledContents(False)
        self.LabelZ.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelZ.setWordWrap(False)
        self.LabelZ.setObjectName("LabelZ")
        self.LabelSpeed = QtWidgets.QLabel(Dialog)
        self.LabelSpeed.setGeometry(QtCore.QRect(480, 210, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LabelSpeed.setFont(font)
        self.LabelSpeed.setAutoFillBackground(True)
        self.LabelSpeed.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LabelSpeed.setLineWidth(1)
        self.LabelSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelSpeed.setObjectName("LabelSpeed")
        self.XValue = QtWidgets.QLCDNumber(Dialog)
        self.XValue.setGeometry(QtCore.QRect(520, 80, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.XValue.setFont(font)
        self.XValue.setAutoFillBackground(False)
        self.XValue.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.XValue.setDigitCount(4)
        self.XValue.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.XValue.setObjectName("XValue")
        self.LabelY = QtWidgets.QLabel(Dialog)
        self.LabelY.setGeometry(QtCore.QRect(490, 120, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LabelY.setFont(font)
        self.LabelY.setTextFormat(QtCore.Qt.PlainText)
        self.LabelY.setScaledContents(False)
        self.LabelY.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelY.setWordWrap(False)
        self.LabelY.setObjectName("LabelY")
        self.LabelX = QtWidgets.QLabel(Dialog)
        self.LabelX.setGeometry(QtCore.QRect(490, 80, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LabelX.setFont(font)
        self.LabelX.setTextFormat(QtCore.Qt.PlainText)
        self.LabelX.setScaledContents(False)
        self.LabelX.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelX.setWordWrap(False)
        self.LabelX.setObjectName("LabelX")
        self.ZJog = QtWidgets.QLineEdit(Dialog)
        self.ZJog.setGeometry(QtCore.QRect(590, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.ZJog.setFont(font)
        self.ZJog.setAlignment(QtCore.Qt.AlignCenter)
        self.ZJog.setObjectName("ZJog")
        self.speed = QtWidgets.QComboBox(Dialog)
        self.speed.setGeometry(QtCore.QRect(520, 240, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.speed.setFont(font)
        self.speed.setObjectName("speed")
        self.LabelGcode = QtWidgets.QLabel(Dialog)
        self.LabelGcode.setGeometry(QtCore.QRect(500, 280, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LabelGcode.setFont(font)
        self.LabelGcode.setAutoFillBackground(True)
        self.LabelGcode.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LabelGcode.setLineWidth(1)
        self.LabelGcode.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelGcode.setObjectName("LabelGcode")
        self.gcodeManual = QtWidgets.QLineEdit(Dialog)
        self.gcodeManual.setGeometry(QtCore.QRect(480, 300, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.gcodeManual.setFont(font)
        self.gcodeManual.setText("")
        self.gcodeManual.setAlignment(QtCore.Qt.AlignCenter)
        self.gcodeManual.setObjectName("gcodeManual")
        self.SendButton = QtWidgets.QPushButton(Dialog)
        self.SendButton.setGeometry(QtCore.QRect(650, 300, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SendButton.setFont(font)
        self.SendButton.setObjectName("SendButton")
        
        self.instructionText.setReadOnly(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.speed.setFont(font)
        self.speed.setObjectName("speed")
        self.speed.addItem("1")
        self.speed.addItem("2")
        self.speed.addItem("3")
        self.speed.addItem("4")
        self.speed.addItem("5")
        self.speed.setCurrentIndex(2)
        self.right_shortcut = QtWidgets.QShortcut(QtGui.QKeySequence("right"), Dialog)
        self.right_shortcut.activated.connect(lambda: tinyG.jog("X",0.5,200))
        self.right_shortcut.activated.connect(lambda: self.updatePosition(tinyG))
        self.left_shortcut = QtWidgets.QShortcut(QtGui.QKeySequence("left"), Dialog)
        self.left_shortcut.activated.connect(lambda: tinyG.jog("X",-0.5,200))
        self.left_shortcut.activated.connect(lambda: self.updatePosition(tinyG))
        self.up_shortcut = QtWidgets.QShortcut(QtGui.QKeySequence("up"), Dialog)
        self.up_shortcut.activated.connect(lambda: tinyG.jog("Y",0.5,200))
        self.up_shortcut.activated.connect(lambda: self.updatePosition(tinyG))
        self.down_shortcut = QtWidgets.QShortcut(QtGui.QKeySequence("down"), Dialog)
        self.down_shortcut.activated.connect(lambda: tinyG.jog("Y",-0.5,200))
        self.down_shortcut.activated.connect(lambda: self.updatePosition(tinyG))
        self.zero_shortcut = QtWidgets.QShortcut(QtGui.QKeySequence("PgDown"), Dialog)
        self.zero_shortcut.activated.connect(lambda: tinyG.jog("Z",-0.5,200))
        self.zero_shortcut.activated.connect(lambda: self.updatePosition(tinyG))
        self.one_shortcut = QtWidgets.QShortcut(QtGui.QKeySequence("PgUp"), Dialog)
        self.one_shortcut.activated.connect(lambda: tinyG.jog("Z",0.5,200))
        self.one_shortcut.activated.connect(lambda: self.updatePosition(tinyG))
        self.GoButton.setDefault(True)
        self.Instructions.clicked.connect(lambda: self.openInstructions())
        self.runMill.clicked.connect(lambda: self.runMilling(tinyG,probeCommands, Dialog))
        self.GoButton.clicked.connect(lambda: self.callJog(tinyG))
        self.xyOrigin.clicked.connect(lambda: self.goxyOrigin(tinyG))
        self.resetOrigin.clicked.connect(lambda: self.origin(tinyG))
        self.updatePosition(tinyG)
        
        
        self.retranslateUi(Dialog, probeCommands)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, probeCommands):
        commandText=""
        counter=0
        for i in probeCommands:
            counter=counter+1
            commandText=commandText+"Procedure #"+str(counter)+"\nType: " +i.procedureType+"\n"+ "Parameters: "+i.parameter+"\nCurrent Depth: "+str(int(i.millingDepth*1000))+"\u03BCm\n\n"
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Milling Configurations"))
        self.label_2.setText(_translate("Dialog", "Created at University of Minnesota"))
        self.instructionText.setPlainText(_translate("Dialog", commandText))
        self.procedureNumber.setText(_translate("Dialog", "1"))
        self.depthValue.setText(_translate("Dialog", "50"))
        self.runMill.setText(_translate("Dialog", "Run Mill"))
        self.LabelPosition_2.setText(_translate("Dialog", "<html><head/><body><p>Add Milling Depth (μm)</p></body></html>"))
        self.LabelPosition_3.setText(_translate("Dialog", "<html><head/><body><p>Procedure Number</p></body></html>"))
        self.resetOrigin.setText(_translate("Dialog", "Reset Origin"))
        self.Instructions.setText(_translate("Dialog", "?"))
        self.xyOrigin.setText(_translate("Dialog", "Go to XY Origin"))
        self.GoButton.setText(_translate("Dialog", "Go!"))
        self.label_3.setText(_translate("Dialog", "Set Position"))
        self.XJog.setText(_translate("Dialog", "0"))
        self.LabelJog.setText(_translate("Dialog", "Jog (mm)"))
        self.LabelPosition.setText(_translate("Dialog", "Position (mm)"))
        self.YJog.setText(_translate("Dialog", "0"))
        self.LabelZ.setText(_translate("Dialog", "Z"))
        self.LabelSpeed.setText(_translate("Dialog", "Speed (1-5)"))
        self.LabelY.setText(_translate("Dialog", "Y"))
        self.LabelX.setText(_translate("Dialog", "X"))
        self.ZJog.setText(_translate("Dialog", "0"))
        self.LabelGcode.setText(_translate("Dialog", "G-code command"))
        self.SendButton.setText(_translate("Dialog", "Send"))
