
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-15T08:28:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4ed82a4d80d2bb3d06559c66d19a32023e790e8",
 "version": "3.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
